
#default production profile
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
logging:
  config: classpath:/logging/logback-prod.xml


---

#default devo profile

spring:
  profiles: devo
  mvc:
    view:
      suffix: .html
      prefix: /
logging:
  config: src/main/resources/logging/logback-dev.xml